import type { Metadata } from "next";
import { IBM_Plex_Sans } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const IBMPlexSans = IBM_Plex_Sans({
  variable: "--font-IBM-plex-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${IBMPlexSans.variable} antialiased text-white`}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
